### ISSUE TITLE
Pending tasks after client close

### ISSUE THREAD

**Issue by decaz** [tipsi/aiozk#18]
After interrupting of process I'm getting pending tasks error. Is it a bug or I have to change handling of client close?

`test_zk.py`:
```python
import asyncio
import signal

from aiozk import ZKClient

loop = asyncio.get_event_loop()
zk = ZKClient('localhost')


async def run():
    await zk.start()


async def stop_handler():
    await zk.close()
    loop.stop()


loop.add_signal_handler(
    signal.SIGINT, lambda: asyncio.ensure_future(stop_handler()))
loop.run_until_complete(run())
try:
    loop.run_forever()
finally:
    loop.close()
```
Log:
```
$ python test_zk.py
^CAborting connection to localhost:2181
Task was destroyed but it is pending!
task: <Task pending coro=<Session.repair_loop() running at /home/decaz/.virtualenvs/test/lib/python3.6/site-packages/aiozk/session.py:150> wait_for=<Future finished result=None>>
Task was destroyed but it is pending!
task: <Task pending coro=<Connection.read_loop() running at /home/decaz/.virtualenvs/test/lib/python3.6/site-packages/aiozk/connection.py:154> wait_for=<Future cancelled>>
```

**Comment by cybergrind** [comment]
@decaz hey,
In other tests `client.close()` works pretty well and don't give any warnings.
But if `stop_handler` was called and waited correctly this must be an error in `aiozk`.

**Comment by decaz** [comment]
@cybergrind pending task errors come after `aiozk.session.Session.close()` was awaited. It means that some tasks (`aiozk.session.Session.repair_loop()` and `aiozk.connection.Connection.read_loop()`) are left still running even after close was invoked.

**Comment by cybergrind** [comment]
@decaz  Yep, they definitely still running, but I'm interested why we have errors only in signals workflow and all other `client.close()` in tests are fine.

**Comment by decaz** [comment]
@cybergrind it is because loop is never closed within tests.

We can take simpler snippet (without using `signals`):
```python
import asyncio

from aiozk import ZKClient


async def start():
    await zk.start()
    asyncio.ensure_future(stop())


async def stop():
    await zk.close()
    loop.stop()


zk = ZKClient('localhost')
loop = asyncio.get_event_loop()
loop.run_until_complete(start())
loop.run_forever()
loop.close()
```
This code will output pending tasks errors, but if you comment out the last line (`loop.close()`) then there won't any errors.
