### ISSUE TITLE
ensure_path method always send NodeExists exception to log.

### ISSUE THREAD

**Issue by Soniccube** [tipsi/aiozk#2]
ensure_path method always send NodeExists exception to log when node already exists.

in session.py, send method, logging all the exceptions then raise it again.

**Comment by cybergrind** [comment]
Yeah, it seems like we're catching `NodeExists` errors in `ensure_path` but the underlying method is throwing and logging errors anyway. I'm not sure if we want to change this behavior right now.

**Comment by Soniccube** [comment]
Hope for changing this behavior, anyway I will close this issue ahead.
