### ISSUE TITLE
Exception is raised on session close

### ISSUE THREAD

**Issue by decaz** [tipsi/aiozk#29]
#28 introduced a little bug - now `asyncio.CancelledError` exception is raised on session close.
Here the task is cancelled:
https://github.com/tipsi/aiozk/blob/341b337a2fc239788fc142eba3633868bd3a8bf1/aiozk/session.py#L311
And here its exception is being catched:
https://github.com/tipsi/aiozk/blob/341b337a2fc239788fc142eba3633868bd3a8bf1/aiozk/session.py#L87
As we know `future.exception()` raises `asyncio.CancelledError` if the future has been cancelled so finally we're getting exception raised.

FYI @cybergrind @nikitagromov

**Comment by cybergrind** [comment]
@decaz yeah. Seems not critical but need to fix it
Thank you!

**Comment by cybergrind** [comment]
fixed in #32
