### ISSUE TITLE
Watcher recipes pass old data to callback

### ISSUE THREAD

**Issue by Soniccube** [tipsi/aiozk#3]
In DataWatcher and ChildrenWatcher, it will pass the changing data to callback as parameter. But the data pass into the callback is the old value, not the new value after changing.

Is it designing to act like this? In many other zk clients, like kazoo, this parameter will be the new value, I also think passing the new value to callback is better.

It seems like a mistake in BaseWatcher.

Thanks.

**Comment by cybergrind** [comment]
Hey. Seems like this is require some tests from my side, at first glance, it seems like everything correct
We always return `self.fetch` and it returns new data:

https://github.com/tipsi/aiozk/blob/staging/aiozk/recipes/data_watcher.py#L11
https://github.com/tipsi/aiozk/blob/staging/aiozk/recipes/children_watcher.py#L11

The main issue with `zoonado` library (we've just ported it to asyncio with minimal modifications) that it has no integration tests with actual zookeeper instance, just unit tests. 
So we're going to implement this new tests, but now recipes may contain errors and mistakes.

**Comment by cybergrind** [comment]
@Soniccube if you're interested in this library maybe you could write me to `cybergrind at gmail.com` and we may discuss current state and further development plans

**Comment by Soniccube** [comment]
It did return the result of self.fetch(), but it self.fetch() called before the change event happened.

https://github.com/tipsi/aiozk/blob/staging/aiozk/recipes/base_watcher.py#L35-L46

the event happens in L43 when self.fetch() called in L39.

It has the same issue with zoonado.

**Comment by cybergrind** [comment]
@Soniccube yeah, definitely misplaced code line

**Comment by livercat** [comment]
Even after this fix, aiozk recipes ChildrenWatch and DataWatch have a difference in behavior compared to the kazoo recipes: in kazoo, both these watches [also trigger right after they're registered](http://kazoo.readthedocs.io/en/latest/api/recipe/watchers.html). In aiozk, they only trigger on events. Is this a desirable behavior?

**Comment by cybergrind** [comment]
@livercat I believe we should have behavior similar to kazoo. Thank you for notice
